In [135]:
b = []
import requests
from bs4 import BeautifulSoup

url = "https://ru.wikipedia.org/wiki/Категория:Поэты_Казахстана"
page = requests.get(url).text
soup = BeautifulSoup(page, 'lxml')
links = soup.find('div', id='mw-pages').find_all('a')
for a in links:
    url = 'https://ru.wikipedia.org/wiki/' + a.get('title')
    b.append(url)
    
    
url = "https://ru.wikipedia.org/wiki/Категория:Писатели_Казахстана"
page = requests.get(url).text
soup = BeautifulSoup(page, 'lxml')
links = soup.find('div', id='mw-pages').find_all('a')
for a in links:
    url = 'https://ru.wikipedia.org/wiki/' + a.get('title')
    b.append(url)
    
    
url = "https://ru.wikipedia.org/wiki/Категория:Философы_Казахстана"
page = requests.get(url).text
soup = BeautifulSoup(page, 'lxml')
links = soup.find('div', id='mw-pages').find_all('a')
for a in links:
    url = 'https://ru.wikipedia.org/' + a.get('title')
    b.append(url)
    
    
url = "https://ru.wikipedia.org/wiki/Категория:Народные_герои_Казахстана"
page = requests.get(url).text
soup = BeautifulSoup(page, 'lxml')
links = soup.find('div', id='mw-pages').find_all('a')
for a in links:
    url = 'https://ru.wikipedia.org/wiki/' + a.get('title')
    b.append(url)
    
    
url = "https://ru.wikipedia.org/wiki/Категория:Лауреаты_Государственной_премии_Республики_Казахстан"
page = requests.get(url).text
soup = BeautifulSoup(page, 'lxml')
links = soup.find('div', id='mw-pages').find_all('a')
for a in links:
    url = 'https://ru.wikipedia.org/wiki/' + a.get('title')
    b.append(url)
    
    
url = "https://ru.wikipedia.org/wiki/Категория:Казахские_ханы"
page = requests.get(url).text
soup = BeautifulSoup(page)

links = soup.find('div', id='mw-pages').find_all('a')
for a in links:
    url = 'https://ru.wikipedia.org/wiki/' + a.get('title')
    b.append(url)

    
url = "https://ru.wikipedia.org/wiki/Категория:Казахские_бии"
page = requests.get(url).text
soup = BeautifulSoup(page)

links = soup.find('div', id='mw-pages').find_all('a')
for a in links:
    url = 'https://ru.wikipedia.org/wiki/' + a.get('title')
    b.append(url)
    
url = "https://ru.wikipedia.org/wiki/Категория:Казахские_султаны"
page = requests.get(url).text
soup = BeautifulSoup(page)

links = soup.find('div', id='mw-pages').find_all('a')
for a in links:
    url = 'https://ru.wikipedia.org/wiki/' + a.get('title')
    b.append(url)

    
url = "https://ru.wikipedia.org/wiki/Категория:Казахские_батыры"
page = requests.get(url).text
soup = BeautifulSoup(page)

links = soup.find('div', id='mw-pages').find_all('a')
for a in links:
    url = 'https://ru.wikipedia.org/wiki/' + a.get('title')
    g5.append(url)

    
ludi = list(set(b))

Казахские акыны

In [150]:
len(ludi)

695

In [161]:
bday = []
bname = []
dday = []
bplace = []
dplace = []
for i in range(len(ludi)):
    url = ludi[i]
    res = requests.get(url)
    soup = BeautifulSoup(res.text)
    
    if soup.find('span',class_='bday'):
        bname.append(url)
        bday.append(soup.find('span',class_='bday').getText())
        for j in soup.find_all('span',class_="no-wikidata"):
            if 'data-wikidata-property-id="P19"' in str(j):
                bplace.append(j.getText())
        if len(bplace)!=len(bname):
            bplace.append('null')
        if soup.find('span',class_='dday'):
            dday.append(soup.find('span',class_='dday').getText())
            for k in soup.find_all('span',class_="no-wikidata"):
                if 'data-wikidata-property-id="P20"' in str(k):
                    dplace.append(k.getText())
        else:
            dday.append('Null')
        if len(dplace)!=len(bname):
            dplace.append('null')

In [165]:
data = {'Name': bname, 'Bday':bday,'Dday':dday,'Bplace':bplace,'Dplace':dplace}  
  
import pandas as pd
df = pd.DataFrame(data)

In [173]:
df['Name'] = df['Name'].str.replace('https://ru.wikipedia.org/wiki/','')
df['Name'] = df['Name'].str.replace(',','')

/var/folders/0t/88z6_xdx6q74nq0vmzm4fqt40000gn/T/ipykernel_30175/2343587017.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace('https://ru.wikipedia.org/wiki/','')

In [174]:
df

,Name,Bday,Dday,Bplace,Dplace
0,Толе-би,1663,1756,"урочище Коктума, ныне Алакольский район, Казах...","Акбурхан-орда, ныне Толебийский район"
1,Санрык Токтыбайулы,1692,1740,близ современного села Ушарал (Таласский район...,современный Таласский район (Жамбылская област...
2,Джаксыбеков Адильбек Рыскельдинович,1954-07-26,Null,"с. Бурли, Карабалыкский район, Кустанайская об...",null
3,Мусабаев Талгат Амангельдиевич,1951-01-07,Null,"с. Каргалы, Джамбулский район, Алма-Атинская о...",null
4,Кесоглу Лаки Константинович,1939-07-22,Null,"Батуми, Грузинская ССР, СССР",null
...,...,...,...,...,...
537,Сериккали Зейнолла,1938-02-10,2004-03-20,"Курмангазинский район, Гурьевская область, Каз...",Алма-Ата
538,Чокин Шафик Чокинович,1912-10-01,2003-07-04,null,null
539,Амраева Аделия Акимжановна,1986-12-11,Null,null,null
540,Симашко Морис Давидович,1924-03-18,2000-12-15,Одесса,Бат-Ям
541,Турманжанов Утебай Турманжанович,1904-12-13,1978,"селение Бугун,Ордабасынский район, Южно-Казахс...",Алма-Ата

In [172]:
df.to_excel('a.xlsx')

In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('a.xlsx')

In [4]:
df['Name'] = df['Name'].str.replace(',','')

In [10]:
city = pd.read_excel('city.xlsx')

In [11]:
city = city.drop('Unnamed: 0',axis =1)

In [12]:
city.columns = city.loc[1]
city = city.loc[2:]

In [122]:
conditions1 = [
    ((df['Bplace'].astype(str).str.contains('Алма'))&(df['Bplace'].astype(str).str.contains('область'))&(~df['Bplace'].astype(str).str.contains('Талд'))),
    ((df['Bplace'].astype(str).str.contains('Акмол'))|(df['Bplace'].astype(str).str.contains('Кокчетав'))),
    ((df['Bplace'].astype(str).str.contains('Караган'))|(df['Bplace'].astype(str).str.contains('Атасу'))|(df['Bplace'].astype(str).str.contains('Каркарал'))),
    ((df['Bplace'].astype(str).str.contains('Павлодар'))|(df['Bplace'].astype(str).str.contains('Щербактинский'))),
    ((df['Bplace'].astype(str).str.contains('Туркестан'))|(df['Bplace'].astype(str).str.contains('Арыс'))),
    ((df['Bplace'].astype(str).str.contains('Алма'))&(~df['Bplace'].astype(str).str.contains('область'))),
    ((df['Bplace'].astype(str).str.contains('Жамбыл'))|(df['Bplace'].astype(str).str.contains('Джамбул'))),
    ((df['Bplace'].astype(str).str.contains('Кзыл-Ор'))|(df['Bplace'].astype(str).str.contains('Кызылор'))),
    ((df['Bplace'].astype(str).str.contains('Талды-Курган'))|(df['Bplace'].astype(str).str.contains('Талдыкорган'))),
    ((df['Bplace'].astype(str).str.contains('Актюб'))|(df['Bplace'].astype(str).str.contains('Актоб'))|(df['Bplace'].astype(str).str.contains('Алгин'))),
    ((df['Bplace'].astype(str).str.contains('Северо'))|(df['Bplace'].astype(str).str.contains('Петропав'))|(df['Bplace'].astype(str).str.contains('Айыртау'))),
    ((df['Bplace'].astype(str).str.contains('Атырау'))|(df['Bplace'].astype(str).str.contains('Гурьев'))),
    ((df['Bplace'].astype(str).str.contains('Восточно'))|(df['Bplace'].astype(str).str.contains('Улан'))|(df['Bplace'].astype(str).str.contains('ВКО'))),
    ((df['Bplace'].astype(str).str.contains('Шымкент'))&(~df['Bplace'].astype(str).str.contains('область'))),
    ((df['Bplace'].astype(str).str.contains('Южно-Каз'))|(df['Bplace'].astype(str).str.contains('Чимкент'))),
    ((df['Bplace'].astype(str).str.contains('Западно-Каз'))|(df['Bplace'].astype(str).str.contains('Уральск'))),
    ((df['Bplace'].astype(str).str.contains('Алакол'))),
    ((df['Bplace'].astype(str).str.contains('Кустанай'))|(df['Bplace'].astype(str).str.contains('Костанай'))|(df['Bplace'].astype(str).str.contains('Амангел'))),
    ((df['Bplace'].astype(str).str.contains('Семипалатинск'))|(df['Bplace'].astype(str).str.contains('Абай'))|(df['Bplace'].astype(str).str.contains('Семей'))),
    ((df['Bplace'].astype(str).str.contains('Верный'))),
    ((df['Bplace'].astype(str).str.contains('Мангистау'))),
    ((df['Bplace'].astype(str).str.contains('Чунджа'))|(df['Bplace'].astype(str).str.contains('Енбекши'))|(df['Bplace'].astype(str).str.contains('Жаркент'))|(df['Bplace'].astype(str).str.contains('Талгар'))),
    ((df['Bplace'].astype(str).str.contains('Джез'))|(df['Bplace'].astype(str).str.contains('Жезк'))|(df['Bplace'].astype(str).str.contains('Улытау'))),
]
values1 = ['Алматинская область','Акмолинская область','Карагандинская область','Павлодарская область','Туркестанская область',
         'Алматы','Жамбылская область','Кызылординская область','Жетысуская область','Актюбинская область','Северо-Казахстанская область',
         'Атырауская область','Восточно-Казахстанская область','Шымкент','Туркестанская область','Западно-Казахстанская область',
          'Жетысуская область','Костанайская область','Абайская область','Алматы','Мангистауская область','Алматинская область','Улытауская область'
         ]

In [119]:
conditions = [
    ((df['Dplace'].astype(str).str.contains('Алма'))&(df['Dplace'].astype(str).str.contains('область'))&(~df['Dplace'].astype(str).str.contains('Талд'))),
    ((df['Dplace'].astype(str).str.contains('Акмол'))|(df['Dplace'].astype(str).str.contains('Кокчетав'))),
    ((df['Dplace'].astype(str).str.contains('Караган'))|(df['Dplace'].astype(str).str.contains('Атасу'))|(df['Dplace'].astype(str).str.contains('Каркарал'))),
    ((df['Dplace'].astype(str).str.contains('Павлодар'))|(df['Dplace'].astype(str).str.contains('Щербактинский'))),
    ((df['Dplace'].astype(str).str.contains('Туркестан'))|(df['Dplace'].astype(str).str.contains('Арыс'))),
    ((df['Dplace'].astype(str).str.contains('Алма'))&(~df['Dplace'].astype(str).str.contains('область'))),
    ((df['Dplace'].astype(str).str.contains('Жамбыл'))|(df['Dplace'].astype(str).str.contains('Джамбул'))),
    ((df['Dplace'].astype(str).str.contains('Кзыл-Ор'))|(df['Dplace'].astype(str).str.contains('Кызылор'))),
    ((df['Dplace'].astype(str).str.contains('Талды-Курган'))|(df['Dplace'].astype(str).str.contains('Талдыкорган'))),
    ((df['Dplace'].astype(str).str.contains('Актюб'))|(df['Dplace'].astype(str).str.contains('Актоб'))|(df['Dplace'].astype(str).str.contains('Алгин'))),
    ((df['Dplace'].astype(str).str.contains('Северо'))|(df['Dplace'].astype(str).str.contains('Петропав'))|(df['Dplace'].astype(str).str.contains('Айыртау'))),
    ((df['Dplace'].astype(str).str.contains('Атырау'))|(df['Dplace'].astype(str).str.contains('Гурьев'))),
    ((df['Dplace'].astype(str).str.contains('Восточно'))|(df['Dplace'].astype(str).str.contains('Улан'))|(df['Dplace'].astype(str).str.contains('ВКО'))),
    ((df['Dplace'].astype(str).str.contains('Шымкент'))&(~df['Dplace'].astype(str).str.contains('область'))),
    ((df['Dplace'].astype(str).str.contains('Южно-Каз'))|(df['Dplace'].astype(str).str.contains('Чимкент'))),
    ((df['Dplace'].astype(str).str.contains('Западно-Каз'))|(df['Dplace'].astype(str).str.contains('Уральск'))),
    ((df['Dplace'].astype(str).str.contains('Алакол'))),
    ((df['Dplace'].astype(str).str.contains('Кустанай'))|(df['Dplace'].astype(str).str.contains('Костанай'))|(df['Dplace'].astype(str).str.contains('Амангел'))),
    ((df['Dplace'].astype(str).str.contains('Семипалатинск'))|(df['Dplace'].astype(str).str.contains('Абай'))|(df['Dplace'].astype(str).str.contains('Семей'))),
    ((df['Dplace'].astype(str).str.contains('Верный'))),
    ((df['Dplace'].astype(str).str.contains('Мангистау'))),
    ((df['Dplace'].astype(str).str.contains('Чунджа'))|(df['Dplace'].astype(str).str.contains('Енбекши'))|(df['Dplace'].astype(str).str.contains('Жаркент'))|(df['Dplace'].astype(str).str.contains('Талгар'))),
    ((df['Dplace'].astype(str).str.contains('Джез'))|(df['Dplace'].astype(str).str.contains('Жезк'))|(df['Dplace'].astype(str).str.contains('Улытау'))),
]
values = ['Алматинская область','Акмолинская область','Карагандинская область','Павлодарская область','Туркестанская область',
         'Алматы','Жамбылская область','Кызылординская область','Жетысуская область','Актюбинская область','Северо-Казахстанская область',
         'Атырауская область','Восточно-Казахстанская область','Шымкент','Туркестанская область','Западно-Казахстанская область',
          'Жетысуская область','Костанайская область','Абайская область','Алматы','Мангистауская область','Алматинская область','Улытауская область'
         ]

In [123]:
import numpy as np
df['reg'] = np.select(conditions,values)
df['reg1'] = np.select(conditions1,values1)

In [127]:
df2 = df[df['reg1']!='0']
df1 = df[df['reg1']=='0']

In [83]:
for i in range(len(df)):
    if df['Bday'][i]!='Null':
        df['Bday'][i]=df['Bday'][i][:4]
    if df['Dday'][i]!='Null':
        df['Dday'][i]=df['Dday'][i][:4]

/var/folders/0t/88z6_xdx6q74nq0vmzm4fqt40000gn/T/ipykernel_52495/283867090.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Bday'][i]=df['Bday'][i][:4]
/var/folders/0t/88z6_xdx6q74nq0vmzm4fqt40000gn/T/ipykernel_52495/283867090.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Dday'][i]=df['Dday'][i][:4]

In [114]:
df2 = df2.drop('Dplace',axis=1)

In [89]:
df2['Bplace'] = df2['reg']

In [92]:
df2

,Name,Bday,Dday,Bplace,Dplace
0,Толе-би,1663,1756,Жетысуская область,"Акбурхан-орда, ныне Толебийский район"
1,Санрык Токтыбайулы,1692,1740,Жамбылская область,современный Таласский район (Жамбылская област...
2,Джаксыбеков Адильбек Рыскельдинович,1954,Null,Костанайская область,NaN
3,Мусабаев Талгат Амангельдиевич,1951,Null,Алматинская область,NaN
5,Оразалин Нурлан Мыркасымович,1947,Null,Алматинская область,NaN
...,...,...,...,...,...
532,Бактыгереева Акуштап,1944,Null,Западно-Казахстанская область,NaN
535,Бейсенова Алия Сарсеновна,1932,Null,Карагандинская область,NaN
536,Бегалин Сапаргали Искакович,1895,1983,Восточно-Казахстанская область,"Алма-Ата (Казахская ССР, СССР)"
537,Сериккали Зейнолла,1938,2004,Атырауская область,Алма-Ата
541,Турманжанов Утебай Турманжанович,1904,1978,Туркестанская область,Алма-Ата

In [115]:
df2.to_excel('c.xlsx')

In [111]:
for i in range(len(df2)):
    if df2['reg'][i]=='0':
        df2['reg'][i]=df2['Dplace'][i]

/var/folders/0t/88z6_xdx6q74nq0vmzm4fqt40000gn/T/ipykernel_52495/2061199658.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['reg'][i]=df2['Dplace'][i]

In [103]:
df2 = df2.reset_index()

In [112]:
df2['reg'][0]

'Акбурхан-орда, ныне Толебийский район'

In [113]:
df2

,index,Name,Bday,Dday,Bplace,Dplace,reg
0,0,Толе-би,1663,1756,Жетысуская область,"Акбурхан-орда, ныне Толебийский район","Акбурхан-орда, ныне Толебийский район"
1,1,Санрык Токтыбайулы,1692,1740,Жамбылская область,современный Таласский район (Жамбылская област...,Жамбылская область
2,2,Джаксыбеков Адильбек Рыскельдинович,1954,Null,Костанайская область,NaN,NaN
3,3,Мусабаев Талгат Амангельдиевич,1951,Null,Алматинская область,NaN,NaN
4,5,Оразалин Нурлан Мыркасымович,1947,Null,Алматинская область,NaN,NaN
...,...,...,...,...,...,...,...
327,532,Бактыгереева Акуштап,1944,Null,Западно-Казахстанская область,NaN,NaN
328,535,Бейсенова Алия Сарсеновна,1932,Null,Карагандинская область,NaN,NaN
329,536,Бегалин Сапаргали Искакович,1895,1983,Восточно-Казахстанская область,"Алма-Ата (Казахская ССР, СССР)",Алматы
330,537,Сериккали Зейнолла,1938,2004,Атырауская область,Алма-Ата,Алматы
331,541,Турманжанов Утебай Турманжанович,1904,1978,Туркестанская область,Алма-Ата,Алматы

In [116]:
df2.isnull().sum()

index       0
Name        0
Bday        0
Dday        0
Bplace      0
reg       196
dtype: int64

In [118]:
df2.to_csv('c.csv',encoding='utf-8')

In [124]:
df

,Unnamed: 0,Name,Bday,Dday,Bplace,Dplace,reg,reg1
0,0,Толе-би,1663,1756,"урочище Коктума, ныне Алакольский район, Казах...","Акбурхан-орда, ныне Толебийский район",0,Жетысуская область
1,1,Санрык Токтыбайулы,1692,1740,близ современного села Ушарал (Таласский район...,современный Таласский район (Жамбылская област...,Жамбылская область,Жамбылская область
2,2,Джаксыбеков Адильбек Рыскельдинович,1954,Null,"с. Бурли, Карабалыкский район, Кустанайская об...",NaN,0,Костанайская область
3,3,Мусабаев Талгат Амангельдиевич,1951,Null,"с. Каргалы, Джамбулский район, Алма-Атинская о...",NaN,0,Алматинская область
4,4,Кесоглу Лаки Константинович,1939,Null,"Батуми, Грузинская ССР, СССР",NaN,0,0
...,...,...,...,...,...,...,...,...
537,537,Сериккали Зейнолла,1938,2004,"Курмангазинский район, Гурьевская область, Каз...",Алма-Ата,Алматы,Атырауская область
538,538,Чокин Шафик Чокинович,1912,2003,NaN,NaN,0,0
539,539,Амраева Аделия Акимжановна,1986,Null,NaN,NaN,0,0
540,540,Симашко Морис Давидович,1924,2000,Одесса,Бат-Ям,0,0
541,541,Турманжанов Утебай Турманжанович,1904,1978,"селение Бугун,Ордабасынский район, Южно-Казахс...",Алма-Ата,Алматы,Туркестанская область

In [130]:
df1['Bplace'].unique()

array(['Батуми, Грузинская ССР, СССР',
       'Талас, Таласская область, Киргизская ССР, СССР', nan,
       'Ортак,КССР, СССР', 'Букеевская Орда',
       'с. Верхний Сыромяс, Пензенская область, РСФСР, СССР',
       'Урумчи, Синьцзян, КНР', 'Ангарск, Иркутская область, РСФСР, СССР',
       'Таласская область, Киргизская ССР',
       'побережье Эмбы, Киргизская степь, Российская империя',
       'Каракалпакская АССР, Узбекская ССР, СССР',
       'Энгельс, АССР Немцев Поволжья, РСФСР, СССР (ныне — Саратовская область России)',
       'Ленинград, СССР', 'Аткарск, Саратовская область, РСФСР, СССР',
       'Ходжейли, Каракалпакская АССР, Узбекская ССР, СССР',
       'Фрунзе, Киргизская ССР, СССР',
       'ур. Жидебай, Бийский уезд, Томская губерния, Российская империя',
       'с. Мало-Сосновка, Змеиногорский уезд, Томская губерния, Российская империя',
       'Усть-Каменогорский округ Западно-Сибирского генерал-губернаторства, Российская империя',
       'казахская степь', 'Казахстан',
       'совхоз «Кенес»,  Яныкурганский район, Казахская ССР, СССР',
       'Киев, Украинская ССР, СССР',
       'село Байбек  Красноярский район, Астраханская область', 'Тула',
       'Баянаул, Степное генерал-губернаторство[1]',
       'зерносовхоз «Комсомольский»,  Павловский район, Алтайский край',
       'Нарын Худук, Лиманский район, Астраханская область, РСФСР, СССР',
       'с. Лосиха, Змеиногорский уезд, Томская губерния, Российская империя',
       'Рига, Латвийская ССР, СССР',
       'урочище Ешкеольмес, Копальский уезд, Семиреченская область, Российская империя[1]',
       'Керкинский район, Туркменская ССР',
       'аул №1  Сарыкопинской волости,Тургайского уезда Тургайская область, Российская империя',
       'Новосибирск, СССР', 'Барнаул, Российская империя',
       'Кишинёв, Бессарабия',
       'Нальчик,Кабардино-Балкарская АССР, РСФСР, СССР',
       'Читинская область, РСФСР, СССР',
       'с. Караколь, Кулундинский район, Алтайский край, РСФСР, СССР',
       'Хрущёв,Кировоградская область, УССР, СССР', 'г. Тбилиси, СССР',
       'Чирчик (город), Ташкентская область, Узбекская ССР, СССР',
       'ст. Вяземская, Вяземский район, Хабаровский край',
       'Казахское Ханство',
       'аул Матыбулак, Пишпекский уезд, Семиреченская область[1], Российская империя',
       'Сыгнак, Казахское ханство', 'Симбирск',
       'село Краснопавловка, Лозовский район, Харьковская область, Украинская ССР, СССР',
       'Шуманай, Каракалпакстан, СССР', 'Оренбург',
       'Днепропетровск, Днепропетровская область, УССР, СССР',
       'ныне Тарбагатайский аймак, Синьцзян-Уйгурский автономный район, Китай',
       'село Ганюшкино, Денгизский уезд, Букеевская губерния, Казахская АССР, РСФСР',
       'Лесозаводск, Приморский край, РСФСР, СССР', 'Казахское ханство',
       'Присырдарье', 'пос. Карабутак, Киргизская АССР, РСФСР, СССР',
       'Сырдарьинская область, Российская империя',
       'Бина, Азербайджанская ССР', 'Владимир, Российская империя',
       'Шэньси, Китай',
       'Ушкон, Аральский район, Киргизская Автономная Социалистическая Советская Республика, РСФСР, СССР',
       'Дубоссары, Молдавская АССР',
       'с. Савинка, Палласовский кантон, АССР немцев Поволжья,  Нижне-Волжский край, РСФСР, СССР',
       'Ташкент, Узбекская ССР, СССР', 'ныне г. Азов', 'Алтайский край',
       'Баяндай, Джаркентский уезд, Джетысуйская губерния,  Казакская АССР,  РСФСР, СССР[2]',
       'Сакарчага, Туркменская ССР, СССР',
       'а. Жетиарал Бурылшынского района Алтайского округа СУАР КНР',
       'Туапсе', 'Новосибирск, РСФСР', 'Алтайский край, Россия',
       'Курмалай, Володарский район, Сталинградская область, РСФСР, СССР',
       'Туркмения',
       'село Хонихай, Семиреченская область, Российская империя',
       'село Анета, Волынская губерния, Российская империя',
       'Яссы, Казахское ханство', 'Курайлысайский, Алашская автономия',
       'станица Новопавловка, Российская империя', 'Винница',
       'Мукей-Каратас (ныне в Или-Казахском автономном округе Синьцзян-Уйгурском автономного района КНР)',
       'Кульджа, Китай', 'Баянаул, Казахская ССР, СССР',
       'Казахстан, СССР', 'Бугунь, Казахское ханство',
       'Караторгайская волость, Тургайского уезда Тургайская область',
       'село Ават, Верненский уезд, Семиреченская область, Российская империя[1]',
       'Одесса'], dtype=object)

In [157]:
conditions2 = [
    ((df['Bplace'].astype(str).str.contains('Томская'))|(df['Bplace'].astype(str).str.contains('Алтайский'))|(df['Bplace'].astype(str).str.contains('Новопавлов'))|(df['Bplace'].astype(str).str.contains('Володарский район'))|(df['Bplace'].astype(str).str.contains('Новосибирск'))),
    ((df['Bplace'].astype(str).str.contains('Букеевская'))|(df['Bplace'].astype(str).str.contains('Алашская'))),
    ((df['Bplace'].astype(str).str.contains('Казахское Ханство'))|(df['Bplace']=='Казахстан, СССР')|(df['Bplace']=='Казахстан')|(df['Bplace']=='казахская степь')),
    ((df['Bplace'].astype(str).str.contains('Баянаул'))),
    ((df['Bplace'].astype(str).str.contains('Китай'))|(df['Bplace'].astype(str).str.contains('Или-Казахском'))|(df['Bplace'].astype(str).str.contains('КНР'))),
    ((df['Bplace'].astype(str).str.contains('Украин'))|(df['Bplace'].astype(str).str.contains('Одесса'))|(df['Bplace'].astype(str).str.contains('Винница'))|(df['Bplace'].astype(str).str.contains('Волынская'))|df['Bplace'].astype(str).str.contains('Азов')),
    ((df['Bplace'].astype(str).str.contains('Семиреченская'))),
    ((df['Bplace'].astype(str).str.contains('Тургайская'))),
    ((df['Bplace'].astype(str).str.contains('Туркмен'))),
    ((df['Bplace'].astype(str).str.contains('Джетысу'))),
    ((df['Bplace'].astype(str).str.contains('Узбек'))),
    ((df['Bplace'].astype(str).str.contains('Азерб'))),
    ((df['Bplace'].astype(str).str.contains('Тблиси')|(df['Bplace'].astype(str).str.contains('Груз')))), 
    ((df['Bplace'].astype(str).str.contains('Латви'))),
    ((df['Bplace'].astype(str).str.contains('Киргиз'))),
    ((df['Bplace'].astype(str).str.contains('Усть-Каменогор'))),
    pd.notnull((df['Bplace']))
]
values2=['Россия','Западно-Казахстанская область','Астана','Павлодарская область','Китай','Украинa','Алматинская область',
        'Костанайская область','Туркменистан','Жетысуская область','Узбекистан','Азербайджан','Грузия','Латвия','Киргизстан',
         'Восточно-Казахстанская область','Россия'
    
]

In [169]:
conditions2 = [
    ((df['Dplace'].astype(str).str.contains('Томская'))|(df['Dplace'].astype(str).str.contains('Алтайский'))|(df['Dplace'].astype(str).str.contains('Новопавлов'))|(df['Dplace'].astype(str).str.contains('Володарский район'))|(df['Dplace'].astype(str).str.contains('Новосибирск'))),
    ((df['Dplace'].astype(str).str.contains('Букеевская'))|(df['Dplace'].astype(str).str.contains('Алашская'))),
    ((df['Dplace'].astype(str).str.contains('Казахское'))|(df['Dplace']=='Казахстан, СССР')|(df['Dplace']=='Казахстан')|(df['Dplace']=='казахская степь')|(df['Dplace'].astype(str).str.contains('Астана'))),
    ((df['Dplace'].astype(str).str.contains('Баянаул'))),
    ((df['Dplace'].astype(str).str.contains('Китай'))|(df['Dplace'].astype(str).str.contains('Или-Казахском'))|(df['Dplace'].astype(str).str.contains('КНР'))),
    ((df['Dplace'].astype(str).str.contains('Украин'))|(df['Dplace'].astype(str).str.contains('Одесса'))|(df['Dplace'].astype(str).str.contains('Винница'))|(df['Dplace'].astype(str).str.contains('Волынская'))|df['Dplace'].astype(str).str.contains('Азов')),
    ((df['Dplace'].astype(str).str.contains('Семиреченская'))),
    ((df['Dplace'].astype(str).str.contains('Тургайская'))),
    ((df['Dplace'].astype(str).str.contains('Туркмен'))),
    ((df['Dplace'].astype(str).str.contains('Джетысу'))),
    ((df['Dplace'].astype(str).str.contains('Узбек'))|(df['Dplace'].astype(str).str.contains('Ташкент'))),
    ((df['Dplace'].astype(str).str.contains('Азерб'))|(df['Dplace'].astype(str).str.contains('Баку'))),
    ((df['Dplace'].astype(str).str.contains('Тблиси')|(df['Dplace'].astype(str).str.contains('Груз')))), 
    ((df['Dplace'].astype(str).str.contains('Латви'))),
    ((df['Dplace'].astype(str).str.contains('Киргиз'))),
    ((df['Dplace'].astype(str).str.contains('Усть-Каменогор'))|(df['Dplace'].astype(str).str.contains('Восточно'))),
    ((df['Dplace'].astype(str).str.contains('Тараз'))),
    ((df['Dplace'].astype(str).str.contains('Белор'))),
    pd.notnull((df['Dplace']))
]
values2=['Россия','Западно-Казахстанская область','Астана','Павлодарская область','Китай','Украинa','Алматинская область',
        'Костанайская область','Туркменистан','Жетысуская область','Узбекистан','Азербайджан','Грузия','Латвия','Киргизстан',
         'Восточно-Казахстанская область','Россия','Жамбылская область','Белорусь'
    
]

In [170]:

df['reg12'] = np.select(conditions2,values2)

In [171]:
for i in range(len(df)):
    if df['reg'][i]=='0':
        df['reg'][i]= df['reg12'][i]

/var/folders/0t/88z6_xdx6q74nq0vmzm4fqt40000gn/T/ipykernel_52495/2697965450.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reg'][i]= df['reg12'][i]

In [167]:
dfff = df[df['reg']=='0']

In [143]:
df['Bplace'][530]

'Казахское Ханство'

In [162]:
df.isnull().sum()

Unnamed: 0      0
Name            0
Bday            0
Dday            0
Bplace        111
Dplace        357
reg             0
reg1            0
reg12           0
dtype: int64

In [168]:
dfff['Dplace'].unique()

array(['Акбурхан-орда, ныне Толебийский район', nan, 'город Баку',
       'Казахстан', 'Жангала', 'Дели, Индия',
       'возле станции Изоча, западнее города Невеля, Калининская область, РСФСР, СССР',
       'Иргизский уезд Тургайской области Российской империи,совр. Шалкарский район',
       'Нукус, Каракалпакская АССР, Узбекская ССР, СССР',
       'Казахское ханство, Сыгнак', 'Астана, Казахстан',
       'Ташкент, Казахское ханство', 'Калуга, Российская империя',
       'Современный Нуратинский район, Узбекистан',
       'около деревни Декшняны, Молодечненский район, Минская область,Белорусская ССР',
       'Тараз, Казахстан', 'Москва, РСФСР', 'Германия',
       'Элиста, Калмыкия',
       'Сосновецкий лагерь, 5 Тунгутское отделение, центральный лазарет',
       'Новосибирск, Россия', 'Оренбург, СССР',
       'Мекка, Саудовская Аравия', 'СССР', 'Новгород',
       'Усть-Каменогорск, Казахстан', 'Казахское ханство',
       'Уфа, Российская империя', 'Крепость Тасарал, берег Балхаша',
       'ныне Астраханская область', 'ЗКО Теректинский район село Шагатай',
       'город Ташкент', 'совр. Киргизия', 'Мечеть Бекет-ата в Огланды',
       'Омск', 'Восточный Казахстан', 'Тургай, Казахское ханство',
       'местность Майтобе, Киргизия', 'Бухара, Бухарское ханство',
       'Бат-Ям'], dtype=object)

In [173]:
df['Dplace'] = df['reg']
df = df.drop(['reg','reg12'],axis=1)

In [177]:
df.isnull().sum()

Unnamed: 0    0
Name          0
Bday          0
Dday          0
Bplace        0
Dplace        0
dtype: int64

In [178]:
df.to_excel('c.xlsx')

In [179]:
df[df['Dplace']=='0']

,Unnamed: 0,Name,Bday,Dday,Bplace,Dplace
2,2,Джаксыбеков Адильбек Рыскельдинович,1954,Null,Костанайская область,0
3,3,Мусабаев Талгат Амангельдиевич,1951,Null,Алматинская область,0
4,4,Кесоглу Лаки Константинович,1939,Null,Грузия,0
5,5,Оразалин Нурлан Мыркасымович,1947,Null,Алматинская область,0
6,6,Избасарова Гульзада Рахманбердиевна,1946,Null,Киргизстан,0
...,...,...,...,...,...,...
533,533,Искандеров Изим,1906,1970,Алматинская область,0
534,534,Джаганова Алтыншаш Каиржановна,1943,Null,0,0
535,535,Бейсенова Алия Сарсеновна,1932,Null,Карагандинская область,0
538,538,Чокин Шафик Чокинович,1912,2003,0,0
539,539,Амраева Аделия Акимжановна,1986,Null,0,0

In [182]:
df[df['Dday']=='Null'].sort_values('Bday')

,Unnamed: 0,Name,Bday,Dday,Bplace,Dplace
456,456,Таниш султан,1453,Null,Астана,0
467,467,Джаниш-султан,1453,Null,0,0
120,120,Сасык-би,1595,Null,0,0
431,431,Есет Кокиулы,1669,Null,0,0
105,105,Акпан Нурбайулы,1701,Null,0,0
...,...,...,...,...,...,...
132,132,Жумадилов Азамат Тлеуханович,1984,Null,0,0
297,297,Байгожин Сундет Абдрахманович,1984,Null,Костанайская область,0
207,207,Ахметов Адиль Ералиевич,1984,Null,Алматы,0
539,539,Амраева Аделия Акимжановна,1986,Null,0,0
305,305,Ауезхан Сырым Асылханулы,1994,Null,Костанайская область,0